spring:

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 15
      connection-timeout: 20000
      idle-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      javax:
        persistence:
          query:
            timeout: 10000

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  config:
    import: optional:file:.env[.properties]

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: tpa-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        base-url: https://generativelanguage.googleapis.com/v1beta
        chat:
          options:
            model: gemini-1.5-flash

server:
  port: ${PORT}

admin:
  name: ${ADMIN_NAME}
  email: ${ADMIN_EMAIL}
  mobile: ${ADMIN_MOBILE}
  password: ${ADMIN_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

file:
  upload-dir: ./uploads

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

logging:
  level:
    root: info

razorpay:
  api:
    key: ${RAZORPAY_KEY}
    secret: ${RAZORPAY_SECRET}
